# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78f07a214ed86d8d64336eb7343c0fdf214fbd385bcc87a5c1829ccfed00f41ead706ff1f483cf9ff513ce0b2b6a4b4d50e8ded6228d1efbda727c64614fc08b

test:
  secret_key_base: b2c907183f83ec16e7513ce1ecd17cae511174a1ee5b81f76758845bea94617b4c745e9727e70469e2783a5139030ae7c984e022b3872d63f4324f8d71edf85f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
